/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin/invoices'
import { Route as AuthenticatedAdminPatientsRouteImport } from './routes/_authenticated/admin/patients'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminAccountingIndexRouteImport } from './routes/_authenticated/admin/accounting/index'
import { Route as AuthenticatedAdminAccountingEquipmentRouteImport } from './routes/_authenticated/admin/accounting/equipment'
import { Route as AuthenticatedAdminAccountingExpensesRouteImport } from './routes/_authenticated/admin/accounting/expenses'
import { Route as AuthenticatedAdminAccountingIncomeRouteImport } from './routes/_authenticated/admin/accounting/income'
import { Route as AuthenticatedAdminAccountingRecurringRouteImport } from './routes/_authenticated/admin/accounting/recurring'
import { Route as AuthenticatedAdminAccountingReportsRouteImport } from './routes/_authenticated/admin/accounting/reports'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPatientsRoute =
  AuthenticatedAdminPatientsRouteImport.update({
    id: '/patients',
    path: '/patients',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingIndexRoute =
  AuthenticatedAdminAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingEquipmentRoute =
  AuthenticatedAdminAccountingEquipmentRouteImport.update({
    id: '/accounting/equipment',
    path: '/accounting/equipment',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingExpensesRoute =
  AuthenticatedAdminAccountingExpensesRouteImport.update({
    id: '/accounting/expenses',
    path: '/accounting/expenses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingIncomeRoute =
  AuthenticatedAdminAccountingIncomeRouteImport.update({
    id: '/accounting/income',
    path: '/accounting/income',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingRecurringRoute =
  AuthenticatedAdminAccountingRecurringRouteImport.update({
    id: '/accounting/recurring',
    path: '/accounting/recurring',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAccountingReportsRoute =
  AuthenticatedAdminAccountingReportsRouteImport.update({
    id: '/accounting/reports',
    path: '/accounting/reports',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/accounting/equipment': typeof AuthenticatedAdminAccountingEquipmentRoute
  '/admin/accounting/expenses': typeof AuthenticatedAdminAccountingExpensesRoute
  '/admin/accounting/income': typeof AuthenticatedAdminAccountingIncomeRoute
  '/admin/accounting/recurring': typeof AuthenticatedAdminAccountingRecurringRoute
  '/admin/accounting/reports': typeof AuthenticatedAdminAccountingReportsRoute
  '/admin/accounting/': typeof AuthenticatedAdminAccountingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services': typeof ServicesIndexRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/accounting/equipment': typeof AuthenticatedAdminAccountingEquipmentRoute
  '/admin/accounting/expenses': typeof AuthenticatedAdminAccountingExpensesRoute
  '/admin/accounting/income': typeof AuthenticatedAdminAccountingIncomeRoute
  '/admin/accounting/recurring': typeof AuthenticatedAdminAccountingRecurringRoute
  '/admin/accounting/reports': typeof AuthenticatedAdminAccountingReportsRoute
  '/admin/accounting': typeof AuthenticatedAdminAccountingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/services/$slug': typeof ServicesSlugRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/patients': typeof AuthenticatedAdminPatientsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/accounting/equipment': typeof AuthenticatedAdminAccountingEquipmentRoute
  '/_authenticated/admin/accounting/expenses': typeof AuthenticatedAdminAccountingExpensesRoute
  '/_authenticated/admin/accounting/income': typeof AuthenticatedAdminAccountingIncomeRoute
  '/_authenticated/admin/accounting/recurring': typeof AuthenticatedAdminAccountingRecurringRoute
  '/_authenticated/admin/accounting/reports': typeof AuthenticatedAdminAccountingReportsRoute
  '/_authenticated/admin/accounting/': typeof AuthenticatedAdminAccountingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/admin'
    | '/services/$slug'
    | '/services/'
    | '/admin/invoices'
    | '/admin/patients'
    | '/admin/settings'
    | '/admin/'
    | '/admin/accounting/equipment'
    | '/admin/accounting/expenses'
    | '/admin/accounting/income'
    | '/admin/accounting/recurring'
    | '/admin/accounting/reports'
    | '/admin/accounting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/services/$slug'
    | '/services'
    | '/admin/invoices'
    | '/admin/patients'
    | '/admin/settings'
    | '/admin'
    | '/admin/accounting/equipment'
    | '/admin/accounting/expenses'
    | '/admin/accounting/income'
    | '/admin/accounting/recurring'
    | '/admin/accounting/reports'
    | '/admin/accounting'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/services/$slug'
    | '/services/'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/patients'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/accounting/equipment'
    | '/_authenticated/admin/accounting/expenses'
    | '/_authenticated/admin/accounting/income'
    | '/_authenticated/admin/accounting/recurring'
    | '/_authenticated/admin/accounting/reports'
    | '/_authenticated/admin/accounting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/patients': {
      id: '/_authenticated/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AuthenticatedAdminPatientsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/': {
      id: '/_authenticated/admin/accounting/'
      path: '/accounting'
      fullPath: '/admin/accounting/'
      preLoaderRoute: typeof AuthenticatedAdminAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/equipment': {
      id: '/_authenticated/admin/accounting/equipment'
      path: '/accounting/equipment'
      fullPath: '/admin/accounting/equipment'
      preLoaderRoute: typeof AuthenticatedAdminAccountingEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/expenses': {
      id: '/_authenticated/admin/accounting/expenses'
      path: '/accounting/expenses'
      fullPath: '/admin/accounting/expenses'
      preLoaderRoute: typeof AuthenticatedAdminAccountingExpensesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/income': {
      id: '/_authenticated/admin/accounting/income'
      path: '/accounting/income'
      fullPath: '/admin/accounting/income'
      preLoaderRoute: typeof AuthenticatedAdminAccountingIncomeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/recurring': {
      id: '/_authenticated/admin/accounting/recurring'
      path: '/accounting/recurring'
      fullPath: '/admin/accounting/recurring'
      preLoaderRoute: typeof AuthenticatedAdminAccountingRecurringRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/accounting/reports': {
      id: '/_authenticated/admin/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/admin/accounting/reports'
      preLoaderRoute: typeof AuthenticatedAdminAccountingReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminPatientsRoute: typeof AuthenticatedAdminPatientsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminAccountingEquipmentRoute: typeof AuthenticatedAdminAccountingEquipmentRoute
  AuthenticatedAdminAccountingExpensesRoute: typeof AuthenticatedAdminAccountingExpensesRoute
  AuthenticatedAdminAccountingIncomeRoute: typeof AuthenticatedAdminAccountingIncomeRoute
  AuthenticatedAdminAccountingRecurringRoute: typeof AuthenticatedAdminAccountingRecurringRoute
  AuthenticatedAdminAccountingReportsRoute: typeof AuthenticatedAdminAccountingReportsRoute
  AuthenticatedAdminAccountingIndexRoute: typeof AuthenticatedAdminAccountingIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
    AuthenticatedAdminPatientsRoute: AuthenticatedAdminPatientsRoute,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminAccountingEquipmentRoute:
      AuthenticatedAdminAccountingEquipmentRoute,
    AuthenticatedAdminAccountingExpensesRoute:
      AuthenticatedAdminAccountingExpensesRoute,
    AuthenticatedAdminAccountingIncomeRoute:
      AuthenticatedAdminAccountingIncomeRoute,
    AuthenticatedAdminAccountingRecurringRoute:
      AuthenticatedAdminAccountingRecurringRoute,
    AuthenticatedAdminAccountingReportsRoute:
      AuthenticatedAdminAccountingReportsRoute,
    AuthenticatedAdminAccountingIndexRoute:
      AuthenticatedAdminAccountingIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
